@startuml inline_umlgraph_1.svg
[*] -->S_IDLE
S_IDLE --> S_SCANNING : E_ASK_4_SCAN / A_RESET_RAW_SCAN
S_SCANNING --> S_END_SCAN : E_END_SCAN / A_END_SCAN
S_END_SCAN --> S_IDLE : E_ACK_CARTO / A_ACK_4_SCAN
S_IDLE --> S_SAVE : E_SET_CARTO / A_ACK_CARTO
S_SAVE --> S_IDLE : E_ACK_SAVE / A_ACK_4_SAVE_CARTO
S_IDLE --> S_DEATH : E_EXIT / A_EXIT
S_SCANNING --> S_DEATH : E_EXIT / A_EXIT
S_END_SCAN --> S_DEATH : E_EXIT / A_EXIT
S_SAVE --> S_DEATH : E_EXIT / A_EXIT
@enduml
@startuml inline_umlgraph_2.svg
[*] --> S_WAITING
S_WAITING --> S_CONNECTED : E_CONNECTED / A_CONNECTED
S_WAITING --> S_ERROR : E_ERROR / A_ERROR
S_CONNECTED --> S_ERROR : E_ERROR / A_ERROR
S_ERROR --> S_CONNECTED : E_CONNECTED / A_CONNECTED
S_WAITING --> S_WAITING : E_WAITING / A_WAITING
S_ERROR --> S_ERROR : E_ERROR / A_ERROR
S_CONNECTED --> S_CONNECTED : E_CONNECTED / A_CONNECTED
S_CONNECTED --> S_DEATH : E_KILL / A_KILL
S_WAITING --> S_DEATH : E_KILL / A_KILL
S_ERROR --> S_DEATH : E_KILL / A_KILL
@enduml
